# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Wine (1/5)
      run: sudo dpkg --add-architecture i386
    - name: Install Wine (2/5)
      run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
    - name: Install Wine (3/5)
      run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
    - name: Install Wine (4/5)
      run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
    - name: Install Wine (5/5)
      run: sudo apt install --install-recommends winehq-stable
    - run: npm install
    - run: npm run make-release
    - run: npm run make-installer
